CREATE TABLE IF NOT EXISTS public.hits
(
    id          BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app         VARCHAR(512)                NOT NULL,
    uri         VARCHAR(512)                NOT NULL,
    ip          VARCHAR(255)                NOT NULL, --проверить
    date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT stats_pkey PRIMARY KEY (id)
    );

--CREATE TABLE IF NOT EXISTS app
--(
  --  app_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    --app_name VARCHAR(25) NOT NULL,
    --CONSTRAINT pk_app PRIMARY KEY (app_id)
--);

--CREATE TABLE IF NOT EXISTS endpoint_hit
--(
--    endpoint_hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    app_id BIGINT NOT NULL,
--    uri VARCHAR(100) NOT NULL,
--    ip VARCHAR(15) NOT NULL,
--    sent TIMESTAMP NOT NULL,
--    CONSTRAINT pk_endpoint_hit PRIMARY KEY (endpoint_hit_id),
--    CONSTRAINT fk_app_endpoint_hit FOREIGN KEY (app_id) REFERENCES app(app_id) ON DELETE CASCADE
--);